/** Синхронизировано с apps/user-dashboard/src/data.ts (демо). */

export const DEMO_CUSTOMERS = [
  {
    id: 'U-10029',
    name: 'Елена В.',
    avatar: 'EV',
    phone: '+7 916 *** 44-22',
    email: 'elena.v***@gmail.com',
    type: 'b2c',
    ltvStatus: 'Основа',
    consent: { marketing: true, whatsapp: true, telegram: false },
    loyalty: {
      tier: 'Серебро',
      pointsBalance: 1450,
      aiPredictedCLV: 154000,
      churnRisk: 'Средний',
      nextAction: 'Генерация 10% оффера на любимую категорию перед сгоранием баллов.',
    },
    purchases: [
      {
        id: 'TR-991',
        title: 'Весенняя коллекция (Пальто, обувь)',
        date: '2026-03-14',
        price: 42000,
        category: 'Одежда/Обувь',
      },
      {
        id: 'TR-102',
        title: 'Базовый уход (Набор косметики)',
        date: '2025-11-20',
        price: 8500,
        category: 'Красота',
      },
    ],
    history: [
      {
        id: 'ev1',
        date: '2026-03-14 15:30',
        type: 'system',
        sender: 'system',
        content: '[ERP] Транзакция завершена. Начислено 1200 баллов лояльности.',
        status: 'processed',
      },
      {
        id: 'ev2',
        date: '2026-04-18 10:00',
        type: 'whatsapp',
        sender: 'ai',
        content:
          'Елена, здравствуйте! У вас сгорает 1450 баллов через неделю. ИИ собрал персональную подборку новинок на основе ваших прошлых покупок. Использовать бонусы?',
        status: 'read',
      },
      {
        id: 'ev3',
        date: '2026-04-18 10:45',
        type: 'whatsapp',
        sender: 'client',
        content: 'Спасибо! Да, давайте посмотрим, что там интересного.',
        status: 'delivered',
      },
      {
        id: 'ev4',
        date: '2026-04-18 10:46',
        type: 'whatsapp',
        sender: 'ai',
        content:
          'Отлично! Вот ссылка на ваш персональный каталог с уже активированной скидкой: link.to/catalog/EV991. Если нужна помощь — пишите!',
        status: 'delivered',
        revenueImpact: 14500,
      },
    ],
    scoring: {
      lifecycle: 'active',
      churnSegment: 'recovery',
      priorityScore: 74,
      riskIndex: 46,
      daysSincePurchase: 37,
    },
    attributedRevenue30d: 14500,
    savedDiscountRub: 4200,
  },
  {
    id: 'U-88210',
    name: 'ООО «ТехСтрой»',
    avatar: 'ТЧ',
    phone: '+7 495 *** 10-00',
    email: 'procurement@techstroi.ru',
    type: 'b2b',
    ltvStatus: 'VIP',
    consent: { marketing: true, whatsapp: false, telegram: true },
    loyalty: {
      tier: 'VIP',
      pointsBalance: 0,
      aiPredictedCLV: 3500000,
      churnRisk: 'Низкий',
      nextAction: 'Напоминание о продлении сервисного контракта (B2B).',
    },
    purchases: [
      {
        id: 'B2B-1',
        title: 'Сервисный контракт «Корпоративный»',
        date: '2025-05-10',
        price: 450000,
        category: 'B2B Услуги',
      },
      {
        id: 'B2B-2',
        title: 'Оптовая закупка оборудования (Партия 30шт)',
        date: '2025-06-15',
        price: 1200000,
        category: 'Оборудование',
      },
    ],
    history: [
      {
        id: 'tc1',
        date: '2026-04-10 09:00',
        type: 'system',
        sender: 'system',
        content: '[CRM] Приближается срок окончания сервисного контракта.',
        status: 'processed',
      },
      {
        id: 'tc2',
        date: '2026-04-11 11:30',
        type: 'telegram',
        sender: 'ai',
        content:
          'Коллеги, добрый день. ИИ-ассистент на связи. Вижу, что контракт заканчивается в мае. Подготовил спецификацию на продление с учетом вашей индивидуальной скидки. Отправить на email?',
        status: 'read',
      },
      {
        id: 'tc3',
        date: '2026-04-12 14:20',
        type: 'telegram',
        sender: 'client',
        content: 'Да, высылайте на почту. И свяжитесь с нашим юристом.',
        status: 'delivered',
      },
    ],
    scoring: {
      lifecycle: 'dormant',
      churnSegment: 'watch',
      priorityScore: 58,
      riskIndex: 38,
      daysSincePurchase: 310,
    },
    attributedRevenue30d: 0,
    savedDiscountRub: 186000,
  },
  {
    id: 'U-77301',
    name: 'Павел Н.',
    avatar: 'ПН',
    phone: '+7 903 *** 77-01',
    email: 'pavel.n***@yandex.ru',
    type: 'b2c',
    ltvStatus: 'Высокий риск',
    consent: { marketing: true, whatsapp: true, telegram: true },
    loyalty: {
      tier: 'Бронза',
      pointsBalance: 120,
      aiPredictedCLV: 22000,
      churnRisk: 'Высокий',
      nextAction: 'Сценарий win-back: вернуть после 90+ дней без покупки.',
    },
    purchases: [{ id: 'TR-200', title: 'Футболка базовая', date: '2025-12-01', price: 2900, category: 'Одежда' }],
    history: [
      {
        id: 'pn1',
        date: '2026-04-01 11:00',
        type: 'whatsapp',
        sender: 'ai',
        content:
          'Павел, давно не видели! Для вас персональный код RETURN8 на категорию, где вы покупали раньше. Зайти в каталог?',
        status: 'read',
      },
      {
        id: 'pn2',
        date: '2026-04-05 16:20',
        type: 'whatsapp',
        sender: 'client',
        content: 'Ок, киньте ссылку.',
        status: 'delivered',
      },
      {
        id: 'pn3',
        date: '2026-04-05 16:45',
        type: 'system',
        sender: 'system',
        content: '[ERP] Заказ оформлен после касания ИИ (сценарий удержания).',
        status: 'processed',
      },
    ],
    scoring: {
      lifecycle: 'reactivated',
      churnSegment: 'returned',
      priorityScore: 91,
      riskIndex: 72,
      daysSincePurchase: 140,
    },
    attributedRevenue30d: 8900,
    savedDiscountRub: 2100,
  },
];

export const DEMO_QA_DIALOGUES = [
  {
    id: 'qa-1',
    client: 'Александр Т.',
    clientInitials: 'АТ',
    channel: 'whatsapp',
    status: 'warning',
    issue: 'Оценка < 4 в NPS. Риск репутационных потерь.',
    updatedAt: '2026-04-19T16:20:00',
    messages: [
      {
        id: 'm1',
        date: '2026-04-19 15:55',
        sender: 'ai',
        content: 'Александр, спасибо за покупку! Насколько вы довольны доставкой по шкале 1–5?',
      },
      {
        id: 'm2',
        date: '2026-04-19 16:02',
        sender: 'client',
        content: '2. Курьер опоздал на два часа и грубо ответил, когда я позвонил.',
      },
      {
        id: 'm3',
        date: '2026-04-19 16:05',
        sender: 'ai',
        content:
          'Жаль, что так вышло. Чем мы можем исправить ситуацию? Могу передать кейс менеджеру и предложить компенсацию.',
      },
      {
        id: 'm4',
        date: '2026-04-19 16:18',
        sender: 'client',
        content: 'Хочу публичный ответ и возврат доставки.',
      },
    ],
  },
  {
    id: 'qa-2',
    client: 'Мария В.',
    clientInitials: 'МВ',
    channel: 'telegram',
    status: 'intercepted',
    issue: 'Запрос на скидку выше установленного лимита 15%.',
    managerNote: 'Перехвачено менеджером: Анна С.',
    updatedAt: '2026-04-18T11:40:00',
    messages: [
      { id: 'm1', date: '2026-04-18 11:10', sender: 'ai', content: 'Мария, максимальная скидка по правилам бренда — 15% на эту категорию.' },
      { id: 'm2', date: '2026-04-18 11:22', sender: 'client', content: 'У конкурентов 25%, дадите столько же?' },
      { id: 'm3', date: '2026-04-18 11:35', sender: 'system', content: '[Система] Диалог передан менеджеру из-за лимита скидки.' },
    ],
  },
  {
    id: 'qa-3',
    client: 'ООО «АльфаТрейд»',
    clientInitials: 'АТ',
    channel: 'whatsapp',
    status: 'success',
    issue: 'Успешный up-sell: расширенный тариф и техподдержка.',
    updatedAt: '2026-04-17T14:00:00',
    messages: [
      {
        id: 'm1',
        date: '2026-04-17 13:20',
        sender: 'ai',
        content:
          'Коллеги, напоминаю: лицензия истекает в конце месяца. Готов счёт на продление + пакет техподдержки со скидкой для постоянных клиентов.',
      },
      { id: 'm2', date: '2026-04-17 13:45', sender: 'client', content: 'Ок, выставляйте счёт, оплатим в среду.' },
      {
        id: 'm3',
        date: '2026-04-17 13:50',
        sender: 'ai',
        content: 'Отправил счёт на почту и продублировал ссылку здесь. Если нужны правки в спецификации — напишите.',
      },
    ],
  },
  {
    id: 'qa-4',
    client: 'Ирина К.',
    clientInitials: 'ИК',
    channel: 'sms',
    status: 'active',
    issue: 'Клиент уточняет условия акции «Весна».',
    updatedAt: '2026-04-20T09:15:00',
    messages: [
      {
        id: 'm1',
        date: '2026-04-20 09:00',
        sender: 'ai',
        content: 'Ирина, акция действует до 30 апреля: −10% на вторую позицию в заказе при оплате картой.',
      },
      { id: 'm2', date: '2026-04-20 09:12', sender: 'client', content: 'А на распродажу распространяется?' },
    ],
  },
  {
    id: 'qa-5',
    client: 'Дмитрий П.',
    clientInitials: 'ДП',
    channel: 'email',
    status: 'warning',
    issue: 'Жалоба на спам: клиент просит реже писать.',
    updatedAt: '2026-04-19T10:00:00',
    messages: [
      { id: 'm1', date: '2026-04-19 09:30', sender: 'client', content: 'Здравствуйте, письма каждый день — это перебор, отпишите меня от промо.' },
      {
        id: 'm2',
        date: '2026-04-19 09:45',
        sender: 'ai',
        content: 'Понимаю. Отключил маркетинговые письма, оставил только транзакционные. Извините за дискомфорт.',
      },
    ],
  },
  {
    id: 'qa-6',
    client: 'Сервис «Забота»',
    clientInitials: 'СЗ',
    channel: 'telegram',
    status: 'success',
    issue: 'Сбор NPS после визита — оценка 5.',
    updatedAt: '2026-04-16T18:30:00',
    messages: [
      { id: 'm1', date: '2026-04-16 18:00', sender: 'ai', content: 'Как прошёл визит сегодня? Одним сообщением: что понравилось больше всего?' },
      { id: 'm2', date: '2026-04-16 18:15', sender: 'client', content: '5 из 5, мастер внимательный, всё чисто и вовремя.' },
    ],
  },
];
